Task
antonKsanfTasks/Task-3.1.2 pull request #1
Opened 2024-03-20 21:43 UTC by antonksanf

Task

2024-03-21 07:07 UTC, pdasilem requested changes

2024-03-21 07:07 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controller/AdminController.java
> +        user.setPassword(passwordEncoder.encode(user.getPassword()));
убери это в сервис

2024-03-21 07:07 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controller/AdminController.java
> +        user.setPassword(passwordEncoder.encode(user.getPassword())); // Зашифруйте пароль перед обновлением
аналогично.
опять же, подумай - если юзер не введет новый пароль?

2024-03-21 07:07 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controller/UserController.java
> +        if (principal instanceof UserDetails) {
зачем тебе эта проверка здесь?

2024-03-21 07:07 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/dao/UserDaoImpl.java
> +            return null;
ты хоть в лог что-нибудь выведи...

2024-03-27 13:55 UTC, antonksanf commented on src/main/java/ru/itmentor/spring/boot_security/demo/controller/UserController.java
> +        if (principal instanceof UserDetails) {
Для использования емейла как юзернейм

2024-03-27 13:56 UTC, antonksanf commented
Исправил

2024-03-27 14:54 UTC, pdasilem approved these changes

2024-04-15 17:11 UTC, merged